---
title: "Homework3_Final"
author: Mason Buczek
submission: 06/02/2024
git-hub link: https://github.com/Mason-Buczek/Homework3.git
format: pdf

---
## Load the necessary data, tables, and packages

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(dplyr)
library(GGally)
library(MuMIn)
library(ggeffects)
library(knitr)

# Read in the excel fike
drought_exp <- read_xlsx(path = "/Users/masonbuczek/Envs-193DS/Homework_3/Valliere_etal_EcoApps_Data.xlsx",
                         sheet = "First Harvest")
```

## Preliminary Data Cleaning

```{r}
# Cleaning the Data
drought_exp_clean <- drought_exp %>% 
  clean_names() %>% # nicer column names
  mutate(species_name = case_when( # Create new column with scientific names
    species == "ENCCAL" ~ "Encelia californica", # bush sunflower
    species == "ESCCAL" ~ "Eschscholzia californica", # California poppy
    species == "PENCEN" ~ "Penstemon centranthifolius", # Scarlet bugler
    species == "GRICAM" ~ "Grindelia camporum", # great valley gumweed
    species == "SALLEU" ~ "Salvia leucophylla", # Purple sage
    species == "STIPUL" ~ "Nasella pulchra", # Purple needlegrass
    species == "LOTSCO" ~ "Acmispon glaber" # deerweed
  )) %>% 
  relocate(species_name, .after = species) %>% # Move species_name column after species
  mutate(water_treatment = case_when( # adding column with full treatment names
    water == "WW" ~ "Well watered",
    water == "DS" ~ "Drought stressed"
  )) %>% 
  relocate(water_treatment, .after = water) # Move water_treatment column after water

# Model Construction

# Model 0: Null model
model0 <- lm(total_g ~ 1, # formula
             data = drought_exp_clean) # data frame

# Model 1: Saturated Model
model1 <- lm(total_g ~ sla + water_treatment + species_name,
             data = drought_exp_clean)
par(mfrow = c(2, 2))

# Model 2: Model total biomass as a function of SLA and water treatment
model2 <- lm(total_g ~ sla + water_treatment,
             data = drought_exp_clean)
par(mfrow = c(2, 2))

# Model 3: Model total biomass as a function of SLA and species
model3 <- lm(total_g ~ sla + species_name,
             data = drought_exp_clean)
par(mfrow = c(2, 2))

#Model 4: (My own model) Model total biomass as a function of water treatment only
model4 <- lm(total_g ~ water_treatment,
             data = drought_exp_clean)
par(mfrow = c(2, 2))

```

# Problem 1: Multiple linear regression: model selection and construction (52 points)

## Part A: Make a table or list of all the models from class and the last one you constructed on your own. Write a caption for your table. (8 points)

```{r}
# Create a data frame to store the model information
model_table <- data.frame(
  ModelNumber = 0:4,
  Predictors = c(
    "(Null Model) No predictors",
    "SLA, Water Treatment, Species",
    "SLA, Water Treatment",
    "SLA, Species",
    "Water Treatment Only")
)

# Rename the column
colnames(model_table)[1] <- "Model Number"

# Store the models in a list
models <- list(model0, model1, model2, model3, model4)

# Calculate AIC for each model
model_table$AIC <- sapply(models, AIC)

# Calculate delta AIC relative to the model with the lowest AIC
model_table$delta_AIC <- model_table$AIC - min(model_table$AIC)

# Rename the column
colnames(model_table)[4] <- "Delta AIC"

table_caption <- "Model Predictors for Predicting Total Biomass\n\n
This table provides an overview of the structure of the 5 models constructed\n
to predict total biomass. The null model does not include any predictors, while\n
the saturated model incorporates specific leaf area (SLA), water treatment, and\n
species as predictors. There are 3 additional models, two involve SLA and water\n
treatment or SLA and species as predictors with the final model having the only\n
predictor of water treatment"

# Print the table with title, caption, and centered column names
print(kable(model_table, "markdown", caption = table_caption, align = "c"))
```



